# Generated by Django 6.1 on 2026-09-01 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_truckstop_id', models.IntegerField(unique=True)),
                ('truckstop_name', models.CharField(max_length=255)),
                ('address', models.CharField(blank=True, max_length=500)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=3, max_digits=6)),
            ],
            options={
                'indexes': [models.Index(fields=['state'], name='fuel_fuelst_state_641286_idx'), models.Index(fields=['city'], name='fuel_fuelst_city_f05e48_idx'), models.Index(fields=['retail_price'], name='fuel_fuelst_retail__3784a3_idx')],
            },
        ),
    ]
