# Generated by Django 6.1 on 2026-09-01 04:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_truckstop_id',
            field=models.IntegerField(),
        ),
    ]
