# Generated by Django 6.1 on 2026-09-01 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0002_alter_fuelstation_opis_truckstop_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='fuelstation',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='fuelstation',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_truckstop_id',
            field=models.IntegerField(),
        ),
    ]
