# Generated by Django 6.1 on 2026-09-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuel', '0003_fuelstation_latitude_fuelstation_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_truckstop_id',
            field=models.IntegerField(),
        ),
    ]
